theme: jekyll-theme-minimal
title: Ashley Allen
logo: /assets/images/profile.jpeg
description: Hi, my name's Ashley. I'm a programmer based in London, UK. I love solving complex problems efficiently and cleanly. I also love games, playing them and making them. You can see some of my small game projects here.
google_analytics: UA-148448851-1
