theme: jekyll-theme-minimal
title: Ashley Allen
logo: /assets/images/profile.jpeg
description: Recent computer science graduate with games-industry experience, strong programming skills and in-depth knowledge of and love for game development
google_analytics: UA-148448851-1
