theme: jekyll-theme-minimal
title: Ashley Allen
logo: /assets/images/profile.jpeg
description: 4th-year undergraduate student studying Mathematical Computation at University College London
google_analytics: UA-148448851-1
